services:
  - type: web
    name: crowdescrow
    runtime: node
    repo: https://github.com/itsmypritam/Crowdfund
    branch: master
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: CONTRACT_ID
        sync: false
      - key: STELLAR_NETWORK
        value: testnet
