services:
  - type: web
    name: crowdescrow
    runtime: node
    repo: https://github.com/itsmypritam/Crowdfund
    branch: master
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: CONTRACT_ID
        sync: false
      - key: STELLAR_NETWORK
        value: testnet
      - key: PUBLIC_PLAUSIBLE_DOMAIN
        value: warriorpinto-6k1ikg.stormkit.dev
      - key: PUBLIC_GA_MEASUREMENT_ID
        value: G-XXXXXXXXXX
