app = "crowdescrow-backend"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[build]


[env]
  STELLAR_NETWORK = "testnet"
  HORIZON_URL = "https://horizon-testnet.stellar.org"
  POLL_INTERVAL = "5"


[experimental]
  auto_rollback = true


[[services]]
  internal_port = 3001
  protocol = "tcp"
  auto_scaling = false

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
